### ISSUE TITLE
Removal of connection property is case-sensitive

### ISSUE THREAD

**Issue by pderaaij** [hisco/http2-client#10]
The client removes the connection property, but as it is case sensitive it still passes on a `connection` property. 

This should be case insensitive.

**Comment by hisco** [comment]
Just to make sure I understand you correctly:

Are you referring to the removal of the connection property from the http2 headers sent to the server?

**Comment by pderaaij** [comment]
Correct.

**Comment by hisco** [comment]
Fixed in 1.3.2.
Thanks!
