### ISSUE TITLE
http2-client doesn't work in Node 12

### ISSUE THREAD

**Issue by pimterry** [hisco/http2-client#30]
As far as I can tell, this project doesn't work at all in node 12.

I'm testing with Node 12.18.3 (the current node LTS release), and all HTTP/2 requests are never successfully sent to the server. 

Easy to reproduce: `npm test` for this project fails, with every http2 test timing out.

Any ideas why? Happy to help get this fixed, but pointers in the right direction would be very useful!

**Comment by MikeRalphson** [comment]
Could be related to https://github.com/Mermade/oas-kit/issues/244 - if so, the regression was introduced in Node 12.17.0, and though a similar regression was fixed in the Node 14.x line, it hasn't yet been backported to 12.x

**Comment by pimterry** [comment]
@MikeRalphson spot on, thanks! I can confirm the tests pass fine in Node 12.16, but just not 12.17+. Eugh.

Is there a Node bug somewhere documenting the underlying issue?

**Comment by MikeRalphson** [comment]
I don't think anyone's tracked down the 'bad' commit or its revert yet. It would probably take some bisecting.

**Comment by MikeRalphson** [comment]
Related: https://github.com/nodejs/node/pull/34859
