### ISSUE TITLE
Real ip is leaked, on requesting with proxy.

### ISSUE THREAD

**Issue by samsha1** [hisco/http2-client#33]
Hi, While I request via proxy to [ifconfig.me ](https://ifconfig.me/) my real IP is leaked. Shouldn't it be showing my proxy agent IP?

Is there any option to turn off the Forwarded IP?

**Comment by hisco** [comment]
This is a module for http 2 communication from you local machine - Thus ifconfig.me sees your machine ip.
I think what you are looking for is an anonymous proxy service.
